spring:
  datasource:
    url: jdbc:mariadb://192.100.50.100:33307/test
    username: "test_user"
    password: "test_user#1234"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

server:
  servlet:
    session:
      timeout: 30m

logging:
  level:
    "[org.hibernate.SQL]": debug
